services:
  ksrpc:
    image: ${OCI_IMAGE_REF}
    container_name: ${KSRPC_CONTAINER_NAME}
    restart: always
    command: ["python", "-u", "-m", "gunicorn", "-c", "/etc/ksrpc/gunicorn.conf.py", "ksrpc.run_gunicorn:web_app"]
    env_file:
      - .env
    environment:
      TZ: Asia/Shanghai
      CONFIG_SERVER: /etc/ksrpc/config_server.py
    volumes:
      - "./gunicorn.conf.py:/etc/ksrpc/gunicorn.conf.py:ro"
      - "./config_server.py:/etc/ksrpc/config_server.py:ro"
      - "./data/cache:/opt/ksrpc/cache"
    ports:
      - "${KSRPC_HOST_PORT}:8080"
